INSERT INTO public.lorry_plates (plate_no)
VALUES
('46 MAJUMAS'),
('ADA URUSAN-BALIK KAMPUNG'),
('ADA URUSAN-BAYAR LESEN'),
('ADA URUSAN-BAYAR SAMAN'),
('ADA URUSAN-BINI BERSALIN'),
('ADA URUSAN-BINI MATERNITY CHECK UP'),
('ADA URUSAN-BUAT IC'),
('ADA URUSAN-HUJAN LEWAT MARI (SEBAB PAKAI MOTOR)'),
('ADA URUSAN-KENDURI SAUDARA KAHWIN'),
('ADA URUSAN-KERETA ROSAK')
ON CONFLICT (plate_no) DO NOTHING;